-- MySQL Script generated by MySQL Workbench
-- mié 12 abr 2023 14:26:52 CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Soscorro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Soscorro` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Soscorro` ;

-- -----------------------------------------------------
-- Table `Soscorro`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Soscorro`.`Usuarios` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Soscorro`.`Users_has_friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Soscorro`.`Users_has_friends` (
  `userId` INT NOT NULL,
  `friendId` INT NOT NULL,
  PRIMARY KEY (`userId`, `friendId`),
  INDEX `fk_Usuarios_has_Usuarios_Usuarios1_idx` (`friendId` ASC),
  INDEX `fk_Usuarios_has_Usuarios_Usuarios_idx` (`userId` ASC),
  CONSTRAINT `fk_Usuarios_has_Usuarios_Usuarios`
    FOREIGN KEY (`userId`)
    REFERENCES `Soscorro`.`Usuarios` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Usuarios_Usuarios1`
    FOREIGN KEY (`friendId`)
    REFERENCES `Soscorro`.`Usuarios` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Soscorro`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Soscorro`.`mensajes` (
  `messageID` INT NOT NULL AUTO_INCREMENT,
  `creatorId` INT NOT NULL,
  `forumId` INT NOT NULL,
  `fechaUltimaModificacion` DATE NOT NULL,
  `fechaCreacion` DATE NOT NULL,
  `data` VARCHAR(2000),
  PRIMARY KEY (`messageID`),
  INDEX `fk_mensajes_Usuarios1_idx` (`creatorId` ASC),
  INDEX `fk_mensajes_Usuarios2_idx` (`forumId` ASC),
  CONSTRAINT `fk_mensajes_Usuarios1`
    FOREIGN KEY (`creatorId`)
    REFERENCES `Soscorro`.`Usuarios` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensajes_Usuarios2`
    FOREIGN KEY (`forumId`)
    REFERENCES `Soscorro`.`Usuarios` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO Usuarios (userName)
VALUES 
("Javi"),
("Victor"),
("Andres");

INSERT INTO Users_has_friends
VALUES 
(0,1),
(1,2),
(2,0);

INSERT INTO mensajes 
VALUES 
(0,1,'1999-12-10','Hola que tal'),
(1,2,'2000-12-11','Hola buenas tardes'),
(2,0,'2013-11-11','Buenas tardes');

SELECT * FROM mensajes;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
